### ISSUE TITLE
sphinx-build: error: argument -d/--maxdepth: invalid int value: '_build/doctrees-readthedocs'

### ISSUE THREAD

**Issue by jakirkham** [rtfd/readthedocs-build#44]
Ran into the following issue trying to build our docs recently. Maybe a compatibility issue between Read the Docs and Sphinx 1.7.

```
Running Sphinx v1.7.1
loading translations [en]... done
making output directory...
usage: usage: sphinx-build [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
sphinx-build: error: argument -d/--maxdepth: invalid int value: '_build/doctrees-readthedocs'
```

ref: https://readthedocs.org/projects/dask-image/builds/6832288/

**Comment by oruebel** [comment]
@jakirkham I'm seeing the same issue. Did you manage to find a workaround?

**Comment by stsewd** [comment]
@oruebel here https://github.com/rtfd/readthedocs.org/issues/3769 is a little more of info about this issue

**Comment by jakirkham** [comment]
Sorry for duping myself. 😞 Forgot this was already opened.

**Comment by jakirkham** [comment]
Added a workaround that solved the issue for me in [this comment]( https://github.com/rtfd/readthedocs.org/issues/1139#issuecomment-398083449 ).
