### ISSUE TITLE
Move config handling parts of build repo into readthedocs.org

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs-build#50]
As per our discussion on #46, we will be moving at least the config parsing and tests back into readthedocs.org. This will require (at least) the following work items:

- [x] Create a `config` package path on readthedocs.org
- [x] Port tests to new package. Perhaps break this out into its own PR if possible.
- [x] Port config parsing and validation code to readthedocs.org. We should reduce the intermediate layer that combines the config from this package and the database config. This will instead be part of the config parsing when ported to readthedocs.org. 
- [x] Porting the config parsing/validation should respect database fields. Make sure to break existing tests by combining database field values in tests fixture data.
- [ ] Make a PR here removing these pieces

The PR on readthedocs.org is going to be pretty large. I'm not sure if there is a good plan to do this in smaller pieces.

**Comment by stsewd** [comment]
> We should reduce the intermediate layer that combines the config from this package and the database config. This will instead be part of the config parsing when ported to readthedocs.org.

I thinking in injecting this values into the `env_config` attribute, maybe having its own key (`defaults` or sort of). With this we don't need the `ConfigWrapper` object anymore.

**Comment by stsewd** [comment]
>  Make a PR here removing these pieces

I don't understand this very clear. Is it necessary to remove all that code here? Maybe we want to add a note in the readme or maybe `archive` this repository.

**Comment by agjohnson** [comment]
Hrm, yeah, maybe a deprecation notice on the readme! I think we can close this after

**Comment by stsewd** [comment]
I opened #51
